---
title: "p8105_hw5_dd2948"
author: "David DeStephano"
date: "November 3, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(purrr)
```

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

##Problem 1
```{r}
set_missing <- function(x) {
  if(is.numeric(x)){
    #x = replace_na(x, round(mean(x, na.rm=TRUE), digits=1))
    x[is.na(x)] <- round(mean(x, na.rm=TRUE))
    return(x)
  }
  else if (is.character(x)) {
    #x = replace_na(x,"virginica")
    x[is.na(x)] <- "virginica"
    return(x)
  }
}

#map(iris_with_missing, set_missing) 

```

ORIGNAL
```{r}
head(iris_with_missing)
```
VS
```{r}
iris_no_missing<-map(iris_with_missing, set_missing) %>% as.data.frame()
head(iris_no_missing)

```

##Problem 2
```{r, message=FALSE, warning=FALSE,}
setwd("./hw5_data")
files = list.files()
all<-map(files, read_csv) %>% 
  bind_rows() %>% 
  mutate(name=files,
         name=str_remove(name,".csv")) %>% 
  separate(name, c('arm', 'subject'), sep="_") %>% 
  select(subject, arm, everything()) %>% 
  pivot_longer(week_1:week_8,
               names_to = "week",
               values_to="values") %>% 
  mutate(week=str_remove(week,"week_"),
         week=as.numeric(week),
         subject=as.numeric(subject))

head(all)
  
```
Spaghetti plot
```{r}
all %>% ggplot(aes(x = week, y = values,  group=interaction(subject, arm), color = arm)) +
  geom_line() +
  geom_point()+ 
  viridis::scale_fill_viridis(discrete = TRUE)
```